// Raft consensus protocol messages, following the RPC definitions in
// Figure 2 of "In Search of an Understandable Consensus Algorithm"
// (Ongaro and Ousterhout, 2014).
//
// To regenerate Go code, run this from the repository root. Keep it on ONE
// line: a trailing space after a "\" line-continuation makes zsh treat each
// flag as its own command (the "command not found: --go_out=." error).
//
//   protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/raft/proto/raft.proto
//
// This writes raft.pb.go (message types) and raft_grpc.pb.go (client stubs +
// server service code). Requires both plugins on your PATH:
//
//   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/raft/proto/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaftMessage is the envelope for every message exchanged between nodes.
// It carries the paper's common RPC fields: `term` is the sender's
// currentTerm (an argument in requests, the "currentTerm, for the caller
// to update itself" in responses), and `from` identifies the sender
// (the paper's candidateId in RequestVote and leaderId in AppendEntries).
type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender Node ID
	From uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// Recipient Node ID
	To uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	// Sender's currentTerm
	Term uint64 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RaftMessage_RequestVote
	//	*RaftMessage_RequestVoteResponse
	//	*RaftMessage_AppendEntries
	//	*RaftMessage_AppendEntriesResponse
	Payload       isRaftMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetPayload() isRaftMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RaftMessage) GetRequestVote() *RequestVoteRequest {
	if x != nil {
		if x, ok := x.Payload.(*RaftMessage_RequestVote); ok {
			return x.RequestVote
		}
	}
	return nil
}

func (x *RaftMessage) GetRequestVoteResponse() *RequestVoteResponse {
	if x != nil {
		if x, ok := x.Payload.(*RaftMessage_RequestVoteResponse); ok {
			return x.RequestVoteResponse
		}
	}
	return nil
}

func (x *RaftMessage) GetAppendEntries() *AppendEntriesRequest {
	if x != nil {
		if x, ok := x.Payload.(*RaftMessage_AppendEntries); ok {
			return x.AppendEntries
		}
	}
	return nil
}

func (x *RaftMessage) GetAppendEntriesResponse() *AppendEntriesResponse {
	if x != nil {
		if x, ok := x.Payload.(*RaftMessage_AppendEntriesResponse); ok {
			return x.AppendEntriesResponse
		}
	}
	return nil
}

type isRaftMessage_Payload interface {
	isRaftMessage_Payload()
}

type RaftMessage_RequestVote struct {
	RequestVote *RequestVoteRequest `protobuf:"bytes,4,opt,name=request_vote,json=requestVote,proto3,oneof"`
}

type RaftMessage_RequestVoteResponse struct {
	RequestVoteResponse *RequestVoteResponse `protobuf:"bytes,5,opt,name=request_vote_response,json=requestVoteResponse,proto3,oneof"`
}

type RaftMessage_AppendEntries struct {
	AppendEntries *AppendEntriesRequest `protobuf:"bytes,6,opt,name=append_entries,json=appendEntries,proto3,oneof"`
}

type RaftMessage_AppendEntriesResponse struct {
	AppendEntriesResponse *AppendEntriesResponse `protobuf:"bytes,7,opt,name=append_entries_response,json=appendEntriesResponse,proto3,oneof"`
}

func (*RaftMessage_RequestVote) isRaftMessage_Payload() {}

func (*RaftMessage_RequestVoteResponse) isRaftMessage_Payload() {}

func (*RaftMessage_AppendEntries) isRaftMessage_Payload() {}

func (*RaftMessage_AppendEntriesResponse) isRaftMessage_Payload() {}

// RequestVoteRequest is invoked by candidates to gather votes (§5.2).
// The candidate's term and candidateId are carried by the enclosing
// RaftMessage (`term` and `from`).
type RequestVoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of candidate's last log entry (§5.4).
	LastLogIndex uint64 `protobuf:"varint,1,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	// Term of candidate's last log entry (§5.4).
	LastLogTerm   uint64 `protobuf:"varint,2,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

// RequestVoteResponse is the result of a RequestVote RPC. The voter's
// currentTerm, for the candidate to update itself, is carried by the
// enclosing RaftMessage (`term`).
type RequestVoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True means candidate received vote.
	VoteGranted   bool `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

// LogEntry is a single entry in the replicated log. Each entry contains
// a command for the state machine, and the term when the entry was
// received by the leader; the first index is 1 (§5.3).
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position of the entry in the log.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Term when the entry was received by the leader.
	Term uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// Command for the state machine, opaque to Raft.
	Command       []byte `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

// AppendEntriesRequest is invoked by the leader to replicate log entries
// (§5.3); also used as heartbeat (§5.2). The leader's term and leaderId
// are carried by the enclosing RaftMessage (`term` and `from`); followers
// use the leader ID to redirect clients.
type AppendEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of log entry immediately preceding new ones.
	PrevLogIndex uint64 `protobuf:"varint,1,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	// Term of prev_log_index entry.
	PrevLogTerm uint64 `protobuf:"varint,2,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	// Log entries to store (empty for heartbeat; may send more than one
	// for efficiency).
	Entries []*LogEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	// Leader's commitIndex.
	LeaderCommit  uint64 `protobuf:"varint,4,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

// AppendEntriesResponse is the result of an AppendEntries RPC. The
// follower's currentTerm, for the leader to update itself, is carried
// by the enclosing RaftMessage (`term`).
type AppendEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if follower contained entry matching prev_log_index and
	// prev_log_term.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_internal_raft_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_raft_proto_raft_proto protoreflect.FileDescriptor

const file_internal_raft_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/raft/proto/raft.proto\x12\x04raft\"\xfc\x02\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12=\n" +
	"\frequest_vote\x18\x04 \x01(\v2\x18.raft.RequestVoteRequestH\x00R\vrequestVote\x12O\n" +
	"\x15request_vote_response\x18\x05 \x01(\v2\x19.raft.RequestVoteResponseH\x00R\x13requestVoteResponse\x12C\n" +
	"\x0eappend_entries\x18\x06 \x01(\v2\x1a.raft.AppendEntriesRequestH\x00R\rappendEntries\x12U\n" +
	"\x17append_entries_response\x18\a \x01(\v2\x1b.raft.AppendEntriesResponseH\x00R\x15appendEntriesResponseB\t\n" +
	"\apayload\"^\n" +
	"\x12RequestVoteRequest\x12$\n" +
	"\x0elast_log_index\x18\x01 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x02 \x01(\x04R\vlastLogTerm\"8\n" +
	"\x13RequestVoteResponse\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\"N\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x18\n" +
	"\acommand\x18\x03 \x01(\fR\acommand\"\xaf\x01\n" +
	"\x14AppendEntriesRequest\x12$\n" +
	"\x0eprev_log_index\x18\x01 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x02 \x01(\x04R\vprevLogTerm\x12(\n" +
	"\aentries\x18\x03 \x03(\v2\x0e.raft.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x04 \x01(\x04R\fleaderCommit\"1\n" +
	"\x15AppendEntriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x97\x01\n" +
	"\aRaftRPC\x12B\n" +
	"\vRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n" +
	"\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponseBFZDgithub.com/IvanObreshkov/raft-lease-guard/internal/raft/proto;raftpbb\x06proto3"

var (
	file_internal_raft_proto_raft_proto_rawDescOnce sync.Once
	file_internal_raft_proto_raft_proto_rawDescData []byte
)

func file_internal_raft_proto_raft_proto_rawDescGZIP() []byte {
	file_internal_raft_proto_raft_proto_rawDescOnce.Do(func() {
		file_internal_raft_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_raft_proto_raft_proto_rawDesc), len(file_internal_raft_proto_raft_proto_rawDesc)))
	})
	return file_internal_raft_proto_raft_proto_rawDescData
}

var file_internal_raft_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_raft_proto_raft_proto_goTypes = []any{
	(*RaftMessage)(nil),           // 0: raft.RaftMessage
	(*RequestVoteRequest)(nil),    // 1: raft.RequestVoteRequest
	(*RequestVoteResponse)(nil),   // 2: raft.RequestVoteResponse
	(*LogEntry)(nil),              // 3: raft.LogEntry
	(*AppendEntriesRequest)(nil),  // 4: raft.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 5: raft.AppendEntriesResponse
}
var file_internal_raft_proto_raft_proto_depIdxs = []int32{
	1, // 0: raft.RaftMessage.request_vote:type_name -> raft.RequestVoteRequest
	2, // 1: raft.RaftMessage.request_vote_response:type_name -> raft.RequestVoteResponse
	4, // 2: raft.RaftMessage.append_entries:type_name -> raft.AppendEntriesRequest
	5, // 3: raft.RaftMessage.append_entries_response:type_name -> raft.AppendEntriesResponse
	3, // 4: raft.AppendEntriesRequest.entries:type_name -> raft.LogEntry
	1, // 5: raft.RaftRPC.RequestVote:input_type -> raft.RequestVoteRequest
	4, // 6: raft.RaftRPC.AppendEntries:input_type -> raft.AppendEntriesRequest
	2, // 7: raft.RaftRPC.RequestVote:output_type -> raft.RequestVoteResponse
	5, // 8: raft.RaftRPC.AppendEntries:output_type -> raft.AppendEntriesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_raft_proto_raft_proto_init() }
func file_internal_raft_proto_raft_proto_init() {
	if File_internal_raft_proto_raft_proto != nil {
		return
	}
	file_internal_raft_proto_raft_proto_msgTypes[0].OneofWrappers = []any{
		(*RaftMessage_RequestVote)(nil),
		(*RaftMessage_RequestVoteResponse)(nil),
		(*RaftMessage_AppendEntries)(nil),
		(*RaftMessage_AppendEntriesResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_raft_proto_raft_proto_rawDesc), len(file_internal_raft_proto_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_raft_proto_raft_proto_goTypes,
		DependencyIndexes: file_internal_raft_proto_raft_proto_depIdxs,
		MessageInfos:      file_internal_raft_proto_raft_proto_msgTypes,
	}.Build()
	File_internal_raft_proto_raft_proto = out.File
	file_internal_raft_proto_raft_proto_goTypes = nil
	file_internal_raft_proto_raft_proto_depIdxs = nil
}
