// Raft consensus protocol messages, following the RPC definitions in
// Figure 2 of "In Search of an Understandable Consensus Algorithm"
// (Ongaro and Ousterhout, 2014).
//
// To regenerate Go code, run this from the repository root. Keep it on ONE
// line: a trailing space after a "\" line-continuation makes zsh treat each
// flag as its own command (the "command not found: --go_out=." error).
//
//   protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/raft/proto/raft.proto
//
// This writes raft.pb.go (message types) and raft_grpc.pb.go (client stubs +
// server service code). Requires both plugins on your PATH:
//
//   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: internal/raft/proto/raft.proto

package raftpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftRPC_Send_FullMethodName = "/raft.RaftRPC/Send"
)

// RaftRPCClient is the client API for RaftRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RaftRPC is the peer-to-peer transport. Every node runs this server and dials
// every other node's. A node "receives" by handling its peers' Send calls; a
// Raft reply travels later as a separate Send in the other direction.
type RaftRPCClient interface {
	// Send delivers one RaftMessage to this peer. The reply is empty — Raft
	// responses are themselves RaftMessages, sent back independently.
	Send(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type raftRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftRPCClient(cc grpc.ClientConnInterface) RaftRPCClient {
	return &raftRPCClient{cc}
}

func (c *raftRPCClient) Send(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RaftRPC_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftRPCServer is the server API for RaftRPC service.
// All implementations must embed UnimplementedRaftRPCServer
// for forward compatibility.
//
// RaftRPC is the peer-to-peer transport. Every node runs this server and dials
// every other node's. A node "receives" by handling its peers' Send calls; a
// Raft reply travels later as a separate Send in the other direction.
type RaftRPCServer interface {
	// Send delivers one RaftMessage to this peer. The reply is empty — Raft
	// responses are themselves RaftMessages, sent back independently.
	Send(context.Context, *RaftMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedRaftRPCServer()
}

// UnimplementedRaftRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftRPCServer struct{}

func (UnimplementedRaftRPCServer) Send(context.Context, *RaftMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRaftRPCServer) mustEmbedUnimplementedRaftRPCServer() {}
func (UnimplementedRaftRPCServer) testEmbeddedByValue()                 {}

// UnsafeRaftRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftRPCServer will
// result in compilation errors.
type UnsafeRaftRPCServer interface {
	mustEmbedUnimplementedRaftRPCServer()
}

func RegisterRaftRPCServer(s grpc.ServiceRegistrar, srv RaftRPCServer) {
	// If the following call pancis, it indicates UnimplementedRaftRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftRPC_ServiceDesc, srv)
}

func _RaftRPC_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftRPC_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).Send(ctx, req.(*RaftMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftRPC_ServiceDesc is the grpc.ServiceDesc for RaftRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftRPC",
	HandlerType: (*RaftRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _RaftRPC_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/raft/proto/raft.proto",
}
